### PR TITLE
Flesh out the content a bit

### PR DESCRIPTION
**Pull request by SteveBarnett**
@avermeulen, @Onwa2014, @Oyamasiphula: can you have a look at this, please?

This is the first piece of the start of the real ❤️ of this repo. I'll be doing small PRs for each piece as I go along, rather than asking y'all to review a whole big new thing.

### CODE REVIEW

**Comment by avermeulen** [comment]
@SteveBarnett 

A few observations:

Can you add a bit of background about HTML? What it is, why it's cool and maybe why people would use it etc. It feels a bit that it just starts assuming people know what is what in HTMLand.

Describe all the sections of the HTML Document the `html`, `header` and `body` currently only the head is discussed. Also discuss the doctype briefly - why should one care about it for example.

**Comment by SteveBarnett** [comment]
@avermeulen I've added the `html` and `body` tags.

Re background: how down do we want to go? I thought this was picking up from Codecademy, which contains that kind of thing (plus some of this, to be fair). Are we assuming starting from zero in this module?

**Comment by avermeulen** [comment]
@SteveBarnett we just need a brief intro of what it is and why we need it. And if there is a 'good enough' description in Codecademy we should add a link to it.

**Comment by SteveBarnett** [comment]
@avermeulen how's this? https://github.com/codex-academy/HTML/pull/1/commits/db16e3fed769e021a52df787dff51f5bc467dac7

**Pull request merged**
