### PR TITLE
HTML Forms

### PR DESCRIPTION
**Pull request by SteveBarnett**

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@avermeulen, @Onwa2014, @Oyamasiphula: can you have a look at this, please? Thanks!

**Comment by avermeulen** [comment]
@SteveBarnett 

Here are some thoughts:

The 'Pick One' section is moving a very fast - Maybe do an example of each tag. Even if you use your examples you already that is only the tags.

And then the current section that introduces fieldsets - that does everything in an HTML page.

The section on the `name` and `value` attributes needs a heading.

Should the last sentence be part of a section about styling forms?

**Comment by avermeulen** [comment]
@SteveBarnett - please add more details about hidden form variables.

**Comment by SteveBarnett** [comment]
@avermeulen: thanks for the feedback! :)
- Re pick one: hmm, I agree. I've split the input types up, made smaller examples.
- Re fieldsets: oops, that was an error. Now fixed.
- Re section: I don't think it does. It's commentary on the `form-3.html` example. But this bit has been shuffled around anyhoo.
- Re last sentence: removed. This module is all about HTML, so I'm trying to stay away from CSS stuff.
- Re hidden (and password): done.

**Comment by avermeulen** [comment]
@SteveBarnett this looks great now. I like the little examples very nifty. I was wondering if we could make them pop up into their own window? How do you feel about that?

**Comment by SteveBarnett** [comment]
@avermeulen I feel strongly NO! :D  
Opening in a new tab is a user's choice, so we shouldn't do that for them. Also, I've updated the forms actions to be a redirect back to the same section in the docs that they were just reading. That makes me feel that _not_ opening in a new tab is good.

**Comment by SteveBarnett** [comment]
@avermeulen So is that a +1? Shall I merge this in?

@Onwa2014, @Oyamasiphula: any comments?

**Comment by avermeulen** [comment]
You can merge yes. @SteveBarnett

**Pull request merged**
